SRC/final_project/accounts/urls.py
from django.urls import path
from django.contrib.auth import views
from accounts import views

urlpatterns = [

]

SRC/final_project/final_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from authentications.views import *

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  path('', include('authentications.urls')),
                  path('', index, name='index'),
                  path('mail_page/', include('mail_page.urls', namespace='mail_page')),
                  path('accounts/', include('accounts.urls')),
                  path('api-auth/', include('rest_framework.urls')),
                  path('admin_tools_stats/', include('admin_tools_stats.urls')),
              ] + static(settings.STATIC_URL)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SRC/final_project/mail_page/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token

from . import views

from django.views.decorators.csrf import csrf_exempt

app_name = 'mail_page'
urlpatterns = [
    # path('home/', views.home, name='home'),
    path('compose/', views.ComposeEmail.as_view(), name='compose'),
    # signature
    path('newsignature/', views.NewSignature.as_view(), name='newsignature'),
    path('showsignature/', views.ShowSignature.as_view(), name='showsignature'),
    path('deletesignature/<int:id>', views.DeleteSignature.as_view(), name='deletesignature'),
    # path('inbox/', views.Inbox.as_view(), name='inbox'),
    path('inbox/', views.Inbox.as_view(), name='home'),
    path('detail/<int:id>', views.DetailEmail.as_view(), name='detail'),
    path('sent/', views.SentEmail.as_view(), name='sent'),
    path('draftbox/', views.DraftBox.as_view(), name='draftbox'),
    path('createdraft/', views.CreateDraft.as_view(), name='createdraft'),
    path('detaildraft/<int:id>', views.DetailDraft.as_view(), name='detaildraft'),
    path('reply/<int:email_id>', views.reply_email, name='reply'),
    path('showcontacts/', views.ShowContacts.as_view(), name='showcontacts'),
    path('newcontacts/', views.NewContacts.as_view(), name='newcontacts'),
    path('detailcontacts/<int:id>', views.DetailContacts.as_view(), name='detailcontacts'),
    path('deletecontacts/<int:id>', views.DeleteContacts.as_view(), name='deletecontacts'),
    path('updatecontacts/<int:id>', views.UpdateContacts.as_view(), name='updatecontacts'),
    path('emailcontact/<int:id>', views.EmailContact.as_view(), name='emailcontact'),
    # path('emailcontact/<int:id>', views.emailcontct, name='emailcontact'),
    path('contactscsv/', views.contact_csv, name='contactscsv'),
    path('newlabel/', views.NewLabel.as_view(), name='newlabel'),
    path('showlabel/', views.ShowLabel.as_view(), name='showlabel'),
    path('trash/<int:id>', views.Trash.as_view(), name='trash'),
    path('trashbox/', views.TrashBox.as_view(), name='trashbox'),
    path('archive/<int:id>', views.Archive.as_view(), name='archive'),
    path('archivebox/', views.ArchiveBox.as_view(), name='archivebox'),
    path('deleteemail/<int:id>', views.DeleteEmail.as_view(), name='deleteemail'),
    path('forward/<int:id>', views.ForwardEmail.as_view(), name='forward'),
    path('addlabel/<int:email_id>/<int:label_id>', views.AddLabel.as_view(), name='addlabel'),
    path('labeldetail/<int:id>', views.LabelDetail.as_view(), name='labeldetail'),
    path('deletelabel/<int:id>', views.DeleteLabel.as_view(), name='deletelabel'),
    # path('searchemail/', csrf_exempt(views.search_email), name='searchemail'),
    path('filteremail/', views.FilterEmail.as_view(), name='filteremail'),
    path('alpine/', views.FilterAlpineJs.as_view(), name='alpine'),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    path('contacts-api/', views.ContactsApiView.as_view(), name='contacts-api'),
    path('emails-api/', views.EmailsApiView.as_view(), name='emails-api'),
]

SRC/final_project/mail_page/forms.py
from django import forms
from django.forms import RadioSelect

from .models import Email, Contacts, Label, Signature, Filter


class ComposeForm(forms.ModelForm):
    """Form for the new email model"""

    class Meta:
        model = Email
        fields = ['receiver', 'cc', 'bcc', 'subject', 'body', 'file', 'status']


class NewSignatureForm(forms.ModelForm):
    """Form for the new label model"""

    class Meta:
        model = Signature
        fields = ['title']


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Email
        fields = ['subject', 'body', 'file', 'status']


class ForwardForm(forms.ModelForm):
    class Meta:
        model = Email
        fields = ['receiver', 'cc', 'bcc', 'status']
        # widgets = {
        #     'body': forms.Textarea(attrs={'class': 'form-control'})
        # }


class DateInput(forms.DateInput):
    input_type = 'date'


class NewContactForm(forms.ModelForm):
    """Form for the new contact model"""

    class Meta:
        model = Contacts
        fields = ['name', 'email', 'phone_number', 'other_email', 'birth_date']

        widgets = {
            'birthdate': DateInput(),
        }


class NewLabelForm(forms.ModelForm):
    """Form for the new label model"""

    class Meta:
        model = Label
        fields = ['title']


class SearchForm(forms.Form):
    search = forms.CharField()


class FilterForm(forms.ModelForm):
    class Meta:
        model = Filter
        fields = ['sender', 'subject', 'body', 'file']
        # file = forms.TypedChoiceField(widget=forms.RadioSelect)
        file = forms.BooleanField(widget=RadioSelect(choices=[(True, 'Yes'),
                                                              (False, 'No')]))

SRC/final_project/mail_page/views.py
import csv
import json
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import View
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import EmailSerializer, ContactsSerializer
from accounts.models import User
from .forms import ComposeForm, ReplyForm, NewContactForm, NewLabelForm, ForwardForm, SearchForm, \
    NewSignatureForm, FilterForm
from .models import Email, Contacts, Label, Signature
from log import *


class ContactsApiView(APIView):
    def get(self, request):
        user = User.objects.get(pk=request.user.id)
        contacts = Contacts.objects.filter(owner=user)
        serializer = ContactsSerializer(contacts, many=True)
        return Response(serializer.data)


class EmailsApiView(APIView):
    def get(self, request):
        user = User.objects.get(pk=request.user.id)
        emails = Email.objects.filter(user=user)
        serializer = EmailSerializer(emails, many=True)
        return Response(serializer.data)


def cc_bcc(cc, bcc):
    all_receiver = []
    if cc is not None:
        cc_list = cc.split(',')
        all_receiver.extend(cc_list)
    if bcc is not None:
        bcc_list = bcc.split(',')
        all_receiver.extend(bcc_list)
    return all_receiver


class ComposeEmail(LoginRequiredMixin, View):
    """New email compose class"""
    form_class = ComposeForm

    def get(self, request, *args, **kwargs):
        form = self.form_class
        return render(request, 'mail_page/compose.html', {'username': request.user, 'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            if "compose" in request.POST:
                cd = form.cleaned_data
                cc_bcc_list = cc_bcc(cd['cc'], cd['bcc'])
                if cd['receiver'] is not None:
                    cc_bcc_list.append(cd['receiver'])
                receiver_list = list(dict.fromkeys(cc_bcc_list))  # pak kardan tekrariha
                if len(receiver_list) == 0:
                    logger.error(f"{request.user} entered a non-existent user as receiver/cc/bcc ")
                    messages.warning(request, 'message not sent(receiver,bcc,cc=none)', 'warning')
                    return redirect('mail_page:compose')
                else:
                    for rec in receiver_list:
                        if cd['cc'] is not None and rec in cd['cc']:
                            cd['body'] += "\n sent to: " + rec
                        exist_rec = User.objects.filter(username=rec.strip())
                        if exist_rec:
                            user = User.objects.get(id=request.user.id)
                            cd['user'] = user
                            cd['receiver'] = rec.strip()
                            cd['is_draft'] = False
                            if cd['status'] == 'add signature':
                                sig = Signature.objects.filter(owner=request.user)
                                if sig is not None:
                                    sig = sig[0]  # todo: handel
                                    if sig:
                                        cd['body'] += "\n signature: " + sig.title
                            elif cd['status'] == 'none':
                                sig = None
                            Email.objects.create(user=cd['user'], subject=cd['subject'], body=cd['body'],
                                                 signature=sig,
                                                 receiver=cd['receiver'], file=cd['file'], is_draft=cd['is_draft'])
                    messages.success(request, 'email has sent successfully', 'success')
                    # else:
                    #     messages.warning(request, 'you created a new email', 'warning')
                    return redirect('mail_page:home')
            elif "createdraft" in request.POST:
                cd = form.cleaned_data
                # cc_bcc_list = cc_bcc(cd['cc'], cd['bcc'])
                # cc_bcc_list.append(cd['receiver'])
                # receiver_list = list(dict.fromkeys(cc_bcc_list))
                # for rec in receiver_list:
                #     if cd['cc'] is not None and rec in cd['cc']:
                #         cd['body'] += "\n\n sent to: " + rec
                #     exist_rec = User.objects.filter(username=rec.strip())
                #     if exist_rec:
                user = User.objects.get(id=request.user.id)
                cd['user'] = user  # cd['user']= request.user
                #         cd['receiver'] = rec.strip()
                cd['is_draft'] = True
                Email.objects.create(user=cd['user'], subject=cd['subject'], body=cd['body'],
                                     receiver=cd['receiver'], file=cd['file'], is_draft=cd['is_draft'])
                messages.success(request, 'Email drafted', 'success')
                # else:
                #     messages.warning(request, 'you created a new email', 'warning')
            return redirect('mail_page:home')


# class ComposeEmail(LoginRequiredMixin, View):
#     form_class = ComposeForm
#
#     def get(self, request):
#         form = self.form_class
#         return render(request, 'mail_page/compose.html', {'form': form})
#
#     def post(self, request, pk):
#         form = self.form_class(request.POST, request.FILES)
#         # fields = ['receiver', 'subject', 'cc', 'bcc', 'body', 'file', 'signature', 'timestamp']
#         if form.is_valid():
#             cd = form.cleaned_data
#             receiver = User.objects.filter(username__in=cd)
#             new_mail = Email.objects.create(subject=cd['subject'], body=cd['body'],
#                                             file=cd['file'])
#             new_mail.cc.set(receiver)
#             new_mail.bcc.set(receiver)
#             messages.success(request, f'email created successfully', 'success')
#         else:
#             messages.error(request, f'The email account you tried to access does not exist. Please check recipient '
#                                     f'email again.', 'error')
#
#         return render(request, 'mail_page/home.html', {'form': form})

class NewSignature(LoginRequiredMixin, View):
    """New email compose class"""
    form_class = NewSignatureForm

    def setup(self, request, *args, **kwargs):
        self.signature_instance = Signature.objects.filter(owner=request.user)
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        signature = self.signature_instance
        if signature:
            logger.warning(f" user:{request.user} tried to add another signature")
            messages.error(request, 'u already have one signature', 'danger')
            return redirect('mail_page:showsignature')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class
        return render(request, 'mail_page/newsignature.html', {'username': request.user, 'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            newsignature = form.save(commit=False)
            cd = form.cleaned_data
            owner = request.user
            newsignature.owner = owner
            newsignature.save()
            messages.success(request, 'you created a new signature', 'success')
            return redirect('mail_page:showsignature')
        return render(request, 'mail_page/newsignature.html', {'username': request.user, 'form': form})


class ShowSignature(LoginRequiredMixin, View):
    def get(self, request):
        owner = request.user
        signatures = Signature.objects.filter(owner=owner)
        return render(request, 'mail_page/showsignature.html', {'username': request.user, 'signatures': signatures})


class DeleteSignature(LoginRequiredMixin, View):
    def get(self, request, id):
        try:
            signature = get_object_or_404(Signature, pk=id)
            if signature.owner == request.user:
                signature.delete()
                messages.success(request, 'signature deleted successfully', 'success')
            else:
                messages.error(request, 'you cant delete this signature', 'danger')
        except:
            pass
        return redirect('mail_page:showsignature')


class Inbox(LoginRequiredMixin, View):
    """ Email Inbox class """

    def get(self, request):
        perfect_email = 0
        username = request.user
        received = Email.objects.filter(
            (Q(is_trash=False) & Q(is_archived=False) & Q(is_draft=False)) & Q(receiver=username))
        for i in received:
            t1 = int(i.timestamp.timestamp())
            t2 = int(timezone.now().timestamp())
            if 10 >= t2 - t1 >= 0:
                perfect_email += 1
        if perfect_email != 0:
            messages.success(request, f'u have {perfect_email} new messages', 'success')

        return render(request, 'mail_page/home.html', {'username': username, 'all_emails': received})


# class ReplyView(LoginRequiredMixin, View):
#     form_class = ReplyForm
#
#     def post(self, request, email_id):
#         email = get_object_or_404(Email, id=email_id)
#         form = self.form_class(request.POST)
#         if form.is_valid():
#             reply = form.save(commit=False)
#             reply.user = request.user
#             reply.reply = email
#             reply.is_reply = True
#             reply.save()

SRC/final_project/templates/mail_page/archivebox.html
{% extends 'base.html' %}
{% block content %}
    <h2 class="mb-4">Archive</h2>
    {% for email in emails %}
        <p>receiver : {{ email.receiver }}<p>
        <p>user : {{ email.user }}<p>
        <p>timestamp : {{ email.timestamp }}<p>
        <p>subject : {{ email.subject }}</p>
        {% with re=email.id %}
            <button type="submit"><a href="{% url 'mail_page:archive' re %}">Undo</a></button>
            {#            <button type="submit"><a href="{% url 'mail_page:deletetrash' re %}">Delete</a></button> #}
        {% endwith %}
    {% endfor %}
{% endblock %}

SRC/final_project/templates/mail_page/compose.html
{% extends 'base.html' %}
{% block title %} Compose{% endblock %}
{% block content %}
    <h2 class="mb-4">Compose</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        <p>receiver: {{ form.receiver }}</p>
        <p>cc: {{ form.cc }}</p>
        <p>bcc: {{ form.bcc }}</p>
        <p>subject: {{ form.subject }}</p>
        <p>body: {{ form.body|safe }}</p>
        <p>file: {{ form.file }}</p>
        <p>status: {{ form.status }}</p>
        {#        {{ form.as_p }}#}
        <button type="submit" name="compose">Send</button>
        <button type="submit" name="createdraft">Draft</button>
    </form>
{% endblock %}

SRC/final_project/templates/mail_page/contactemail.html
{% extends 'base.html' %}
{% block title %} Contact email {% endblock %}
{% block content %}
    <h2 class="mb-4">Contact email</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>subject: {{ form.subject }}</p>
        <p>body: {{ form.body|safe }}</p>
        <p>file: {{ form.file }}</p>
        {#        {{ form.as_p }}#}
        <button type="submit">Send</button>
    </form>
{% endblock %}

SRC/final_project/templates/mail_page/detail.html
{% extends 'base.html' %}
{#{% include "navbar.html" %}#}
{% block title %} Detail email {% endblock %}
{% block content %}
    <h2 class="mb-4">Detail email</h2>
    <p>from : {{ email.user }}</p>
    {#    <p>cc : {{ email.cc }}</p>#}
    <p>subject : {{ email.subject }}</p>
    <pre>{{ email.body|safe }}</pre>
    {#    <p>file : {{ email.file }}</p>#}
    {% if email.file %}
        <p class="view-message text-left"><span style="color: #0f1712"></span>
            <a href="{{ email.file.url }}" class="fa fa-paperclip" style="color: #d2447f">File</a></p>
    {% endif %}
    {#    <p>signature : {{ email.signature }}</p>#}
    <p>time : {{ email.timestamp }}
    <div style="display:flex; justify-content: flex-start;">

        {% with re=email.id %}
            <button type="submit" class="btn btn-warning dropdown-toggle"><a
                    href="{% url 'mail_page:reply' re %}">Reply</a>
            </button>
            <button type="submit" class="btn btn-warning dropdown-toggle"><a
                    href="{% url 'mail_page:trash' re %}">Trash</a></button>
            <button type="submit" class="btn btn-warning dropdown-toggle"><a href="{% url 'mail_page:archive' re %}">Archive</a>
            </button>
            <button type="submit" class="btn btn-warning dropdown-toggle"><a href="{% url 'mail_page:forward' re %}">Forward</a>
            </button>
            <div class="btn-group dropright">
                <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                    add label
                </button>
                <div class="dropdown-menu">
                    {% for label in labels %}
                        {% with l=label.id %}
                            <a href="{% url 'mail_page:addlabel' re l %}">{{ label.title }}</a>
                        {% endwith %}
                        <br>
                    {% endfor %}
                </div>
            </div>
            </div>

        {% endwith %}
{% endblock %}

SRC/final_project/templates/mail_page/detailcontacts.html
{% extends 'base.html' %}
{% block title %} Detail contacts {% endblock %}
{% block content %}
    <h2 class="mb-4">Detail contacts</h2>
    <p>{{ contact.name }}</p>
    <p>{{ contact.email }}</p>
    <p>{{ contact.phone_number }}</p>
    <p>{{ contact.birth_date }} </p>
    {% with replies=contact.id %}
        <br><br>
        <button type="submit"><a href="{% url 'mail_page:updatecontacts' replies %}">Update</a></button>
        <button type="submit"><a href="{% url 'mail_page:deletecontacts' replies %}">Delete</a></button>
        <button type="submit"><a href="{% url 'mail_page:emailcontact' replies %}">Send email</a></button>
    {% endwith %}
{% endblock %}

SRC/final_project/templates/mail_page/forward.html
{% extends 'base.html' %}
{% block title %} Forward {% endblock %}
{% block content %}
    <h2 class="mb-4">Forward</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">send</button>
    </form>
{% endblock %}

SRC/final_project/templates/mail_page/home.html
{% extends 'base.html' %}
{% block title %}Inbox{% endblock %}
{% block content %}
    <h2 class="mb-4">Inbox</h2>
    <!-- JavaScript Bundle with Popper -->
    <!-- CSS only -->
    {#    <div class="row">#}
    {#        <div class="col-md-8"></div>#}
    {#        <div class="col-md-4">#}
    {#            <div class="form-group">#}
    {#                <input type="text" class="form-control" id="searchField" placeholder="Search">#}
    {#            </div>#}
    {#        </div>#}
    {#    </div>#}

    {#    {% if messages %}#}
    {#        {% for msg in messages %}#}
    {##}
    {#            <div class="alert alert-{{ msg.tags }} alert-dismissible">#}
    {#                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>#}
    {#                <strong>{{ msg }}</strong>#}
    {#            </div>#}
    {##}
    {#        #}
    {#        <div class="alert alert-success alert-dismissible fade show" role="alert">#}
    {#            <p>{{ msg }}</p>#}
    {#<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>#}
    {#        <button type="button" class="btn-close btn-close-white" aria-label="Close"></button>#}
    {#</div>#}
    {#        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>#}
    {#        {% endfor %}#}
    {#    {% endif %}#}
    {% for email in all_emails %}
        <a href="{% url 'mail_page:detail' email.id %}">
            <ul class="message-list">
                <li class="unread">
                    <div class="col col-1"><span class="dot"></span>
                        <div class="checkbox-wrapper">
                            <input type="checkbox" id="chk1">
                            <label for="chk1" class="toggle"></label>
                        </div>
                        <p class="title">{{ email.user.username }}</p><span
                                class="star-toggle glyphicon glyphicon-star-empty"></span>
                    </div>
                    <div class="col col-2">
                        <div class="subject">{{ email.subject }}
                            &nbsp;&ndash;<span class="teaser">{{ email.body|truncatewords:8|safe }}</span>
                        </div>
                        <div class="date">{{ email.timestamp }}</div>
                    </div>
                </li>
            </ul>
        </a>
    {% endfor %}
    {#    <script>#}
    {#        setTimeout(function(){#}
    {#            if ($('#msg').length > 0){#}
    {#              $('#msg').remove();#}
    {#            }#}
    {#        },4000)#}
    {#    </script>#}
{% endblock %}

SRC/final_project/templates/mail_page/inbox.html
{#{% extends 'base.html' %}#}
{#{% block title %}Inbox{% endblock %}#}
{#{% block content %}#}
{#    <h2 class="mb-4">Inbox</h2>#}
{#    {% for email in all_emails %}#}
{#        <a href="{% url 'mail_page:detail' email.id %}">#}
{#            <ul class="message-list">#}
{#                <li class="unread">#}
{#                    <div class="col col-1"><span class="dot"></span>#}
{#                        <div class="checkbox-wrapper">#}
{#                            <input type="checkbox" id="chk1">#}
{#                            <label for="chk1" class="toggle"></label>#}
{#                        </div>#}
{#                        <p class="title">{{ email.user.username }}</p><span#}
{#                                class="star-toggle glyphicon glyphicon-star-empty"></span>#}
{#                    </div>#}
{#                    <div class="col col-2">#}
{#                        <div class="subject">{{ email.subject }}#}
{#                            &nbsp;&ndash;<span class="teaser">{{ email.body|truncatewords:8 }}</span>#}
{#                        </div>#}
{#                        <div class="date">{{ email.timestamp }}</div>#}
{#                    </div>#}
{#                </li>#}
{#            </ul>#}
{#        </a>#}
{#    {% endfor %}#}
{#{% endblock %}#}

SRC/final_project/templates/mail_page/load.html
{% extends 'base.html' %}
{% block title %} Inbox {% endblock %}

<link rel="stylesheet" href="static/mail_page/load.css">
<title>Loading page</title>

{% block content %}
    <div class="load">
        <hr/>
        <hr/>
        <hr/>
        <hr/>
    </div>
{% endblock %}

SRC/final_project/templates/mail_page/newsignature.html
{% extends 'base.html' %}
{% block title %} New Signature {% endblock %}
{% block content %}
    <h2 class="mb-4">New Signature</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">add signature</button>
    </form>
{% endblock %}

SRC/final_project/templates/mail_page/sent.html
{% extends 'base.html' %}
{% block title %} Sent {% endblock %}
{% block content %}
    <h2 class="mb-4">Sent</h2>
    {% for email in sent %}
        <hr style="color: #d39e00">
        <p>{{ email.receiver }}</p>
        {% if email.subject %}
            <p>{{ email.subject }}</p>
        {% else %}
            <p>No subject</p>
        {% endif %}
        {% if email.body %}
            <p>{{ email.body|truncatewords:8|safe }}</p>
        {% else %}
            <p></p>
        {% endif %}
        <p>{{ email.timestamp }}</p>
        {% with detail=email.id %}
            <button type="submit" style="color: #19A68C"><a href="{% url 'mail_page:detail' detail %}">Detail</a>
            </button>
            <button type="submit" style="color: #19A68C">><a href="{% url 'mail_page:trash' detail %}">Trash</a>
            </button>
            <button type="submit" style="color: #19A68C">><a href="{% url 'mail_page:archive' detail %}">Archive</a>
            </button>
        {% endwith %}
    {% endfor %}
{% endblock %}

SRC/final_project/templates/mail_page/showlabel.html
{% extends 'base.html' %}
{% block title %} Show Labels {% endblock %}
{% block content %}
    <h2 class="mb-4">Show Labels</h2>
    {% for label in labels %}
        <hr style="color: #4CAF50">
        {% with replies=label.id %}
            {#            <a href="{% url 'mail_page:labelshowemail' replies %}">#}
            <p>
                <a href="{% url 'mail_page:labeldetail' replies %}">{{ label.title }}</a>
                <br>
                <br>
                <button type="submit"><a href="{% url 'mail_page:labeldetail' replies %}">Emails</a></button>
                <button type="submit"><a href="{% url 'mail_page:deletelabel' replies %}">delete label</a></button>
            </p>
            {#            </a>#}
        {% endwith %}
        <br>
    {% endfor %}
{% endblock %}

SRC/final_project/templates/mail_page/showsignature.html
{% extends 'base.html' %}
{% block title %} Show Signatures {% endblock %}
{% block content %}
    <h2 class="mb-4">Show Signatures</h2>
    {% for signature in signatures %}
        {{ signature.title }}
        {% with replies=signature.id %}
            <p>
                <button type="submit"><a href="{% url 'mail_page:deletesignature' replies %}">
                    delete signature</a></button>
            </p>
        {% endwith %}
    {% endfor %}
{% endblock %}

SRC/final_project/templates/mail_page/trashbox.html
{% extends 'base.html' %}
{% block title %} Trash {% endblock %}
{% block content %}
    <h2 class="mb-4">Trash</h2>
    {% for email in emails %}
        <p>receiver : {{ email.receiver }}<p>
        <p>user : {{ email.user }}<p>
        <p>timestamp : {{ email.timestamp }}<p>
        <p>subject : {{ email.subject }}</p>
        {% with re=email.id %}
            <button type="submit"><a href="{% url 'mail_page:trash' re %}">Undo</a></button>
            <button type="submit"><a href="{% url 'mail_page:deleteemail' re %}">Delete forever</a></button>
            {#            <button type="submit"><a href="{% url 'mail_page:deletetrash' re %}">Delete</a></button> #}
        {% endwith %}
    {% endfor %}
{% endblock %}