SRC/final_project/accounts/urls.py
from django.urls import path
from django.contrib.auth import views
from accounts import views

urlpatterns = [

]

SRC/final_project/final_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from authentications.views import *

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('ckeditor/', include('ckeditor_uploader.urls')),
                  path('', include('authentications.urls')),
                  path('', index, name='index'),
                  path('mail_page/', include('mail_page.urls', namespace='mail_page')),
                  path('accounts/', include('accounts.urls')),
                  path('api-auth/', include('rest_framework.urls')),
                  path('admin_tools_stats/', include('admin_tools_stats.urls')),
              ] + static(settings.STATIC_URL)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SRC/final_project/mail_page/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token

from . import views

from django.views.decorators.csrf import csrf_exempt

app_name = 'mail_page'
urlpatterns = [
    # path('home/', views.home, name='home'),
    path('compose/', views.ComposeEmail.as_view(), name='compose'),
    # signature
    path('newsignature/', views.NewSignature.as_view(), name='newsignature'),
    path('showsignature/', views.ShowSignature.as_view(), name='showsignature'),
    path('deletesignature/<int:id>', views.DeleteSignature.as_view(), name='deletesignature'),
    # path('inbox/', views.Inbox.as_view(), name='inbox'),
    path('inbox/', views.Inbox.as_view(), name='home'),
    path('detail/<int:id>', views.DetailEmail.as_view(), name='detail'),
    path('sent/', views.SentEmail.as_view(), name='sent'),
    path('draftbox/', views.DraftBox.as_view(), name='draftbox'),
    path('createdraft/', views.CreateDraft.as_view(), name='createdraft'),
    path('detaildraft/<int:id>', views.DetailDraft.as_view(), name='detaildraft'),
    path('reply/<int:email_id>', views.reply_email, name='reply'),
    path('showcontacts/', views.ShowContacts.as_view(), name='showcontacts'),
    path('newcontacts/', views.NewContacts.as_view(), name='newcontacts'),
    path('detailcontacts/<int:id>', views.DetailContacts.as_view(), name='detailcontacts'),
    path('deletecontacts/<int:id>', views.DeleteContacts.as_view(), name='deletecontacts'),
    path('updatecontacts/<int:id>', views.UpdateContacts.as_view(), name='updatecontacts'),
    path('emailcontact/<int:id>', views.EmailContact.as_view(), name='emailcontact'),
    # path('emailcontact/<int:id>', views.emailcontct, name='emailcontact'),
    path('contactscsv/', views.contact_csv, name='contactscsv'),
    path('newlabel/', views.NewLabel.as_view(), name='newlabel'),
    path('showlabel/', views.ShowLabel.as_view(), name='showlabel'),
    path('trash/<int:id>', views.Trash.as_view(), name='trash'),
    path('trashbox/', views.TrashBox.as_view(), name='trashbox'),
    path('archive/<int:id>', views.Archive.as_view(), name='archive'),
    path('archivebox/', views.ArchiveBox.as_view(), name='archivebox'),
    path('deleteemail/<int:id>', views.DeleteEmail.as_view(), name='deleteemail'),
    path('forward/<int:id>', views.ForwardEmail.as_view(), name='forward'),
    path('addlabel/<int:email_id>/<int:label_id>', views.AddLabel.as_view(), name='addlabel'),
    path('labeldetail/<int:id>', views.LabelDetail.as_view(), name='labeldetail'),
    path('deletelabel/<int:id>', views.DeleteLabel.as_view(), name='deletelabel'),
    # path('searchemail/', csrf_exempt(views.search_email), name='searchemail'),
    path('filteremail/', views.FilterEmail.as_view(), name='filteremail'),
    path('alpine/', views.FilterAlpineJs.as_view(), name='alpine'),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    path('contacts-api/', views.ContactsApiView.as_view(), name='contacts-api'),
    path('emails-api/', views.EmailsApiView.as_view(), name='emails-api'),
]

SRC/final_project/templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {#    {% block head-extras %}{% endblock %}#}
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <style>{% block style %}{% endblock %}</style>

</head>
<body>
{% include "layout/authentications/__nav.html" %}
{% block content %} {% endblock %}

<script>
    {% block javascript %} {% endblock %}
</script>
</body>
</html>

SRC/final_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    {#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>#}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/mail_page/css/home/style.css">
    <style>
        #sidebar .compose-button {
            border-radius: 100px;
            padding: 13px 20px;
            text-align: center;
            font-weight: 500;
            text-transform: uppercase;
            color: #61C7B3;
            border: 2px solid #61C7B3;
            display: block;
            margin: 0 50px 30px 50px;
            cursor: pointer;
        }

        #sidebar .compose-button:hover {
            color: #ABB4BE;
            border-color: #ABB4BE;
        }
    </style>
</head>
<body>
<div class="wrapper d-flex align-items-stretch">
    {% include "sidebar.html" %}
    <div id="content" class="p-4 p-md-5">
        {% include "navbar.html" %}
        {#    <div class="alert alert-success m-2" id="msg" role="alert" >#}
        {#        Alert!#}
        {#    </div>#}
        {% block content %}{% endblock %}

    </div>
</div>
<script src="/static/mail_page/js/home/jquery.min.js"></script>
<script src="/static/mail_page/js/home/popper.js"></script>
<script src="/static/mail_page/js/home/bootstrap.min.js"></script>
<script src="/static/mail_page/js/home/main.js"></script>
<script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
{{ block.super }}
{#<script src="/static/mail_page/js/home/searchemail.js"></script>#}
</body>
</html>

SRC/final_project/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">

        <button type="button" id="sidebarCollapse" class="btn btn-primary">
            <i class="fa fa-bars"></i>
            <span class="sr-only">Toggle Menu</span>
        </button>
        <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'mail_page:filteremail' %}">Filter</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Setting</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="row">
    <div class="col-md-8">
        {% if messages %}
            {% for msg in messages %}

                <div class="alert alert-{{ msg.tags }} alert-dismissible">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>{{ msg }}</strong>
                </div>

            {% endfor %}
        {% endif %}
    </div>
    <div class="col-md-4">
        <div class="form-group">
            {#            <form action="{% url 'mail_page:alpine' %}" method="post" id="searchForm">#}
            {#                {% csrf_token %}#}
            <input type="text" oninput="searcher(this)" class="form-control"
                   placeholder="Search" name="search">
            {#                <input onclick="searchForm(e)" type="submit" hidden value="">#}
            {#            </form>#}
            <script>
                function searcher(el) {
                    $('#search_list').empty()
                    let search = el.value
                    $.ajax({
                        url: "{% url 'mail_page:alpine' %}",
                        method: 'POST',
                        headers: {
                            'X-CSRFToken': '{{ csrf_token }}'
                        },
                        data: 'search=' + search
                    }).done(function (data) {
                        let emails = JSON.parse(data).list
                        for (let e of emails) {
                            let text = `subject: ${e.subject} sender: ${e.user} receiver: ${e.receiver}`
                            let a = `<a href="/mail_page/detail/${e.id}">${text}</a>`
                            let li = `<li>${a}</li>`
                            $('#search_list').append(li)

                        }
                    })

                }


            </script>
            <ul id="search_list">

            </ul>
        </div>
    </div>
</div>

SRC/final_project/templates/sidebar.html
<nav id="sidebar">
    <div class="p-4 pt-5">
        <div>{{ username }}</div>
        <a href="" class="img logo rounded-circle mb-5" style=""></a>
        <ul class="list-unstyled components mb-5">
            <li>
                <a href="{% url 'mail_page:compose' %}" class="compose-button">Compose</a>
            </li>
            <li>
                <a href="{% url 'mail_page:home' %}">Inbox<span></span></a>
{#                <a href="{% url 'mail_page:home' %}">Inbox<span> (تعداد)</span></a>#}
            </li>
            <li>
                <a href="{% url 'mail_page:sent' %}">Send box</a>
            </li>
            <li>
                <a href="{% url 'mail_page:draftbox' %}">Drafts</a>
            </li>
            <li>
                <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false"
                   class="dropdown-toggle">Contacts</a>
                <ul class="collapse list-unstyled" id="pageSubmenu">
                    {#                <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false"#}
                    {#                   class="dropdown-toggle">Contacts</a>#}
                    {#                <ul class="collapse list-unstyled" id="homeSubmenu">#}
                    <li>
                        <a href="{% url 'mail_page:showcontacts' %}">All contacts</a>
                    </li>
                    <li>
                        <a href="{% url 'mail_page:newcontacts' %}">Add new contacts</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#pageSubmenu1" data-toggle="collapse" aria-expanded="false"
                   class="dropdown-toggle">Labels</a>
                <ul class="collapse list-unstyled" id="pageSubmenu1">
                    <li>
                        <a href="{% url 'mail_page:showlabel' %}">Labels</a>
                    </li>
                    <li>
                        <a href="{% url 'mail_page:newlabel' %}">Add new labels</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#pageSubmenu2" data-toggle="collapse" aria-expanded="false"
                   class="dropdown-toggle">Signature</a>
                <ul class="collapse list-unstyled" id="pageSubmenu2">
                    <li>
                        <a href="{% url 'mail_page:showsignature' %}">Show Signature</a>
                    </li>
                    <li>
                        <a href="{% url 'mail_page:newsignature' %}">New Signature</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="{% url 'mail_page:archivebox' %}">Archive</a>
            </li>
            <li>
                <a href="{% url 'mail_page:trashbox' %}">Trash</a>
            </li>
        </ul>
        <div class="footer">
            <a href="{% url 'logout' %}" target="_blank">Logout</a>
        </div>
    </div>
</nav>